<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="mybot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <link name="base_footprint">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
    </visual>
  </link>


  <joint name="base_footprint_joint" type="fixed">
    <!-- <origin xyz="0 0 ${base_length/2 + caster_radius*2}" rpy="0 0 0" /> -->
    <origin xyz="0 0 1" rpy="0 0 0" />
    <parent link="base_footprint" />
    <child link="base_link" />
  </joint>

  <link name="base_link">
    <visual>
    <!-- <origin xyz=" 0 0 0" rpy="0 0 0" /> -->
      <geometry>
        <box size="0.5 0.5 0.5"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz=" 0 0 0" rpy="0 0 0" />
      <geometry>
        <!-- <cylinder length="${base_length}" radius="${base_radius}" /> -->
        <box size="0.5 0.5 0.5"/>>
      </geometry>
    </collision>
  </link>

</robot>